
import type { Marker, MarkerSet } from './types';

export const INITIAL_MARKER_SETS: MarkerSet[] = [
  { id: 'ohuhu-honolulu-b', name: 'Ohuhu Honolulu B (Brush & Chisel)' },
  // { id: 'ohuhu-kaala', name: 'Ohuhu Kaala (Fine & Chisel)' }, // Removed as per request
  // { id: 'ohuhu-maui', name: 'Ohuhu Maui (Broad & Fine)' }, // Removed as per request
  // { id: 'other', name: 'Other/Uncategorized' }, // Removed to focus on the 120 set
];

const honolulu120SetMarkers: Marker[] = [
  { id: 'R1', name: 'Carmine', hex: '#D1002C', setId: 'ohuhu-honolulu-b' },
  { id: 'R2', name: 'Scarlet', hex: '#ED1C24', setId: 'ohuhu-honolulu-b' },
  { id: 'R3', name: 'Rose Red', hex: '#F15A24', setId: 'ohuhu-honolulu-b' },
  { id: 'R4', name: 'Cherry Pink', hex: '#F26C7D', setId: 'ohuhu-honolulu-b' },
  { id: 'R5', name: 'Coral Pink', hex: '#F69088', setId: 'ohuhu-honolulu-b' },
  { id: 'R6', name: 'Vivid Pink', hex: '#EC008C', setId: 'ohuhu-honolulu-b' },
  { id: 'R7', name: 'Cosmos', hex: '#CE0071', setId: 'ohuhu-honolulu-b' },
  { id: 'R8', name: 'Deep Red', hex: '#94181D', setId: 'ohuhu-honolulu-b' },
  { id: 'R9', name: 'Pale Pink', hex: '#FDECF1', setId: 'ohuhu-honolulu-b' },
  { id: 'R10', name: 'Wine Red', hex: '#790000', setId: 'ohuhu-honolulu-b' },
  { id: 'R11', name: 'Dark Geranium', hex: '#C62930', setId: 'ohuhu-honolulu-b' },
  { id: 'R12', name: 'Rose Pink', hex: '#FBB4C4', setId: 'ohuhu-honolulu-b' },
  { id: 'R13', name: 'Vermillion', hex: '#F26522', setId: 'ohuhu-honolulu-b' },
  { id: 'R14', name: 'Light Pink', hex: '#FED6E0', setId: 'ohuhu-honolulu-b' },
  { id: 'R15', name: 'Geranium', hex: '#EC165D', setId: 'ohuhu-honolulu-b' },
  { id: 'R16', name: 'Lipstick Red', hex: '#BD1030', setId: 'ohuhu-honolulu-b' },
  { id: 'R17', name: 'Pastel Pink', hex: '#FEEFED', setId: 'ohuhu-honolulu-b' },
  { id: 'R18', name: 'Salmon Pink', hex: '#FF8988', setId: 'ohuhu-honolulu-b' },
  { id: 'Y1', name: 'Lemon Yellow', hex: '#FFF500', setId: 'ohuhu-honolulu-b' },
  { id: 'Y2', name: 'Canary Yellow', hex: '#FFEE00', setId: 'ohuhu-honolulu-b' },
  { id: 'Y3', name: 'Yellow', hex: '#FFDD00', setId: 'ohuhu-honolulu-b' },
  { id: 'Y4', name: 'Naples Yellow', hex: '#FDD97B', setId: 'ohuhu-honolulu-b' },
  { id: 'Y5', name: 'Cream', hex: '#FFF7D7', setId: 'ohuhu-honolulu-b' },
  { id: 'Y6', name: 'Honey', hex: '#F8B95A', setId: 'ohuhu-honolulu-b' },
  { id: 'Y7', name: 'Acid Yellow', hex: '#FFF200', setId: 'ohuhu-honolulu-b' },
  { id: 'Y8', name: 'Deep Yellow', hex: '#FFC90E', setId: 'ohuhu-honolulu-b' },
  { id: 'Y9', name: 'Golden Yellow', hex: '#FFC20E', setId: 'ohuhu-honolulu-b' },
  { id: 'Y10', name: 'Pastel Yellow', hex: '#FFFDEB', setId: 'ohuhu-honolulu-b' },
  { id: 'Y11', name: 'Mellow Yellow', hex: '#FFE080', setId: 'ohuhu-honolulu-b' },
  { id: 'Y12', name: 'Barium Yellow', hex: '#F7EA4A', setId: 'ohuhu-honolulu-b' },
  { id: 'Y13', name: 'Buttercup Yellow', hex: '#FAE931', setId: 'ohuhu-honolulu-b' },
  { id: 'Y14', name: 'Pale Cream', hex: '#FFFCE6', setId: 'ohuhu-honolulu-b' },
  { id: 'Y15', name: 'Cadmium Yellow', hex: '#FFEC00', setId: 'ohuhu-honolulu-b' },
  { id: 'YG1', name: 'Yellow Green', hex: '#D0E07A', setId: 'ohuhu-honolulu-b' },
  { id: 'YG2', name: 'Vivid Green', hex: '#8DC63F', setId: 'ohuhu-honolulu-b' },
  { id: 'YG3', name: 'Grass Green', hex: '#39B54A', setId: 'ohuhu-honolulu-b' },
  { id: 'YG4', name: 'Mignonette', hex: '#D6E69C', setId: 'ohuhu-honolulu-b' },
  { id: 'YG5', name: 'Chartreuse', hex: '#BADD78', setId: 'ohuhu-honolulu-b' },
  { id: 'YG6', name: 'Spring Green', hex: '#C4DF9B', setId: 'ohuhu-honolulu-b' },
  { id: 'YG7', name: 'Olive Green', hex: '#698220', setId: 'ohuhu-honolulu-b' },
  { id: 'YG8', name: 'Deep Olive Green', hex: '#55701C', setId: 'ohuhu-honolulu-b' },
  { id: 'G1', name: 'Emerald Green', hex: '#00A651', setId: 'ohuhu-honolulu-b' },
  { id: 'G2', name: 'Forest Green', hex: '#006837', setId: 'ohuhu-honolulu-b' },
  { id: 'G3', name: 'Lime Green', hex: '#8CC63F', setId: 'ohuhu-honolulu-b' },
  { id: 'G4', name: 'Turquoise Green', hex: '#00A99D', setId: 'ohuhu-honolulu-b' },
  { id: 'G5', name: 'Mint Green Light', hex: '#C0E6B0', setId: 'ohuhu-honolulu-b' },
  { id: 'G6', name: 'Ice Green', hex: '#AFDDCD', setId: 'ohuhu-honolulu-b' },
  { id: 'G7', name: 'Pastel Green', hex: '#97D3A9', setId: 'ohuhu-honolulu-b' },
  { id: 'G8', name: 'Apple Green', hex: '#64A541', setId: 'ohuhu-honolulu-b' },
  { id: 'G9', name: 'Peacock Green', hex: '#00806E', setId: 'ohuhu-honolulu-b' },
  { id: 'G10', name: 'Deep Green', hex: '#007B5F', setId: 'ohuhu-honolulu-b' },
  { id: 'G11', name: 'Jade Green', hex: '#00A388', setId: 'ohuhu-honolulu-b' },
  { id: 'G12', name: 'Pale Green', hex: '#E1F0D3', setId: 'ohuhu-honolulu-b' },
  { id: 'G13', name: 'Shadow Green', hex: '#607751', setId: 'ohuhu-honolulu-b' },
  { id: 'B1', name: 'Sky Blue', hex: '#87CEEB', setId: 'ohuhu-honolulu-b' },
  { id: 'B2', name: 'Cobalt Blue', hex: '#0047AB', setId: 'ohuhu-honolulu-b' },
  { id: 'B3', name: 'Peacock Blue', hex: '#008089', setId: 'ohuhu-honolulu-b' },
  { id: 'B4', name: 'Royal Blue', hex: '#4169E1', setId: 'ohuhu-honolulu-b' },
  { id: 'B5', name: 'Cerulean Blue', hex: '#2A52BE', setId: 'ohuhu-honolulu-b' },
  { id: 'B6', name: 'Pastel Blue', hex: '#A2CAE6', setId: 'ohuhu-honolulu-b' },
  { id: 'B7', name: 'Light Blue', hex: '#ADD8E6', setId: 'ohuhu-honolulu-b' },
  { id: 'B8', name: 'Brilliant Blue', hex: '#009EFA', setId: 'ohuhu-honolulu-b' },
  { id: 'B9', name: 'Prussian Blue', hex: '#003153', setId: 'ohuhu-honolulu-b' },
  { id: 'B10', name: 'Ultramarine', hex: '#120A8F', setId: 'ohuhu-honolulu-b' },
  { id: 'B11', name: 'Baby Blue', hex: '#B0E0E6', setId: 'ohuhu-honolulu-b' },
  { id: 'B12', name: 'Ice Blue', hex: '#C6E2FF', setId: 'ohuhu-honolulu-b' },
  { id: 'B13', name: 'Process Blue', hex: '#00AEEF', setId: 'ohuhu-honolulu-b' },
  { id: 'B14', name: 'Aqua Blue', hex: '#00FFFF', setId: 'ohuhu-honolulu-b' },
  { id: 'B15', name: 'Denim Blue', hex: '#1560BD', setId: 'ohuhu-honolulu-b' },
  { id: 'P1', name: 'Lilac', hex: '#C8A2C8', setId: 'ohuhu-honolulu-b' },
  { id: 'P2', name: 'Lavender', hex: '#E6E6FA', setId: 'ohuhu-honolulu-b' },
  { id: 'P3', name: 'Violet', hex: '#8F00FF', setId: 'ohuhu-honolulu-b' },
  { id: 'P4', name: 'Light Violet', hex: '#CF9FFF', setId: 'ohuhu-honolulu-b' },
  { id: 'P5', name: 'Pale Lilac', hex: '#E2CCFF', setId: 'ohuhu-honolulu-b' },
  { id: 'P6', name: 'Vivid Purple', hex: '#9A0EEA', setId: 'ohuhu-honolulu-b' },
  { id: 'P7', name: 'Amethyst', hex: '#9966CC', setId: 'ohuhu-honolulu-b' },
  { id: 'P8', name: 'Mauve Shadow', hex: '#9180A3', setId: 'ohuhu-honolulu-b' },
  { id: 'P9', name: 'Pastel Violet', hex: '#DCD0FF', setId: 'ohuhu-honolulu-b' },
  { id: 'P10', name: 'Deep Violet', hex: '#5D3F99', setId: 'ohuhu-honolulu-b' },
  { id: 'P11', name: 'Pale Purple', hex: '#F3E8FF', setId: 'ohuhu-honolulu-b' },
  { id: 'P12', name: 'Aubergine', hex: '#53315A', setId: 'ohuhu-honolulu-b' },
  { id: 'E1', name: 'Brick Brown', hex: '#AE6A50', setId: 'ohuhu-honolulu-b' },
  { id: 'E2', name: 'Burnt Sienna', hex: '#E97451', setId: 'ohuhu-honolulu-b' },
  { id: 'E3', name: 'Raw Umber', hex: '#826644', setId: 'ohuhu-honolulu-b' },
  { id: 'E4', name: 'Sepia', hex: '#704214', setId: 'ohuhu-honolulu-b' },
  { id: 'E5', name: 'Chocolate', hex: '#7B3F00', setId: 'ohuhu-honolulu-b' },
  { id: 'E6', name: 'Walnut', hex: '#634634', setId: 'ohuhu-honolulu-b' },
  { id: 'E7', name: 'Potato Brown', hex: '#E5C4A3', setId: 'ohuhu-honolulu-b' },
  { id: 'E8', name: 'Sand', hex: '#DABC94', setId: 'ohuhu-honolulu-b' },
  { id: 'E9', name: 'Burnt Umber', hex: '#8A3324', setId: 'ohuhu-honolulu-b' },
  { id: 'E10', name: 'Van Dyke Brown', hex: '#664229', setId: 'ohuhu-honolulu-b' },
  { id: 'E11', name: 'Rose Beige', hex: '#E4C0B1', setId: 'ohuhu-honolulu-b' },
  { id: 'E12', name: 'Raw Silk', hex: '#F2E5D6', setId: 'ohuhu-honolulu-b' },
  { id: 'E13', name: 'Chestnut Brown', hex: '#954535', setId: 'ohuhu-honolulu-b' },
  { id: 'E14', name: 'Ochre', hex: '#CC7722', setId: 'ohuhu-honolulu-b' },
  { id: 'E15', name: 'Dark Suntan', hex: '#AD7A50', setId: 'ohuhu-honolulu-b' },
  { id: 'E16', name: 'Light Suntan', hex: '#E3B991', setId: 'ohuhu-honolulu-b' },
  { id: 'E17', name: 'Powder Pink', hex: '#F9E4D0', setId: 'ohuhu-honolulu-b' }, 
  { id: 'E18', name: 'Dark Brown', hex: '#8B4513', setId: 'ohuhu-honolulu-b' }, 
  { id: 'CG0.5', name: 'Cool Grey 0.5', hex: '#F0F0F0', setId: 'ohuhu-honolulu-b' },
  { id: 'CG1', name: 'Cool Grey 1', hex: '#E6E6E6', setId: 'ohuhu-honolulu-b' },
  { id: 'CG2', name: 'Cool Grey 2', hex: '#D9D9D9', setId: 'ohuhu-honolulu-b' },
  { id: 'CG3', name: 'Cool Grey 3', hex: '#CCCCCC', setId: 'ohuhu-honolulu-b' },
  { id: 'CG4', name: 'Cool Grey 4', hex: '#BFBFBF', setId: 'ohuhu-honolulu-b' },
  { id: 'CG5', name: 'Cool Grey 5', hex: '#A9A9A9', setId: 'ohuhu-honolulu-b' }, 
  { id: 'CG6', name: 'Cool Grey 6', hex: '#999999', setId: 'ohuhu-honolulu-b' },
  { id: 'CG7', name: 'Cool Grey 7', hex: '#808080', setId: 'ohuhu-honolulu-b' },
  { id: 'CG8', name: 'Cool Grey 8', hex: '#666666', setId: 'ohuhu-honolulu-b' },
  { id: 'CG9', name: 'Cool Grey 9', hex: '#4D4D4D', setId: 'ohuhu-honolulu-b' },
  { id: 'WG0.5', name: 'Warm Grey 0.5', hex: '#F5F2EE', setId: 'ohuhu-honolulu-b' },
  { id: 'WG1', name: 'Warm Grey 1', hex: '#EAE4DB', setId: 'ohuhu-honolulu-b' },
  { id: 'WG2', name: 'Warm Grey 2', hex: '#DFD8CC', setId: 'ohuhu-honolulu-b' },
  { id: 'WG3', name: 'Warm Grey 3', hex: '#BCB6AF', setId: 'ohuhu-honolulu-b' }, 
  { id: 'WG4', name: 'Warm Grey 4', hex: '#B0A99F', setId: 'ohuhu-honolulu-b' },
  { id: 'WG5', name: 'Warm Grey 5', hex: '#A1988E', setId: 'ohuhu-honolulu-b' },
  { id: 'WG6', name: 'Warm Grey 6', hex: '#91887D', setId: 'ohuhu-honolulu-b' },
  { id: 'WG7', name: 'Warm Grey 7', hex: '#81786D', setId: 'ohuhu-honolulu-b' },
  { id: 'WG8', name: 'Warm Grey 8', hex: '#72695E', setId: 'ohuhu-honolulu-b' },
  { id: 'WG9', name: 'Warm Grey 9', hex: '#625A4F', setId: 'ohuhu-honolulu-b' },
  { id: '120', name: 'Black', hex: '#000000', setId: 'ohuhu-honolulu-b' },
  { id: '0', name: 'Colorless Blender', hex: '#FFFFFF00', setId: 'ohuhu-honolulu-b' },
];

// Only include markers from the Honolulu 120 set.
export const INITIAL_MARKERS: Marker[] = [...honolulu120SetMarkers];

export const COMMON_COLORS_FILTER = [
  { name: "Red", hexBase: "#FF0000" },
  { name: "Orange", hexBase: "#FFA500" },
  { name: "Yellow", hexBase: "#FFFF00" },
  { name: "Green", hexBase: "#008000" },
  { name: "Blue", hexBase: "#0000FF" },
  { name: "Purple", hexBase: "#800080" },
  { name: "Pink", hexBase: "#FFC0CB" },
  { name: "Brown", hexBase: "#A52A2A" },
  { name: "Grey", hexBase: "#808080" },
  { name: "Black", hexBase: "#000000" },
  { name: "White", hexBase: "#FFFFFF" },
];

